### ISSUE TITLE
The blockchain is halted because the ssl certificate has expired

### ISSUE THREAD

**Issue by ageorge95** [gowke/lotus-blockchain#10]
Peers cannot connect with each other currently, because the ssl certificate used for lotus has expired. It was valid from 19Aug2021 until 19Aug2022, which means that it has expired a couple of days ago.

**Comment by gowke** [comment]
Hi, thanks! Indeed, expired a year after launch! 

I updated the certificates, you may need to update and then run the lotus init again. 
- dont forget to back up the mainnet folder.  after re-generating the ssl certificats with lotus ini, copy the db folder and config back in.

**Comment by ageorge95** [comment]
Hi,
Thank you too for your fast reply !

I have updated my barebone lotus-blockchain repo (https://github.com/ageorge95/lotus-blockchain_BAREBONE_v1.5.0) with the new ssl and everything seems to work OK, currently the blockchain is being synced - I have used your node to connect to (agem.ae:5980), as no other node I tried had the ssl update applied.

I have a recommendation though - you really SHOULD create a release and let people know that the ssl has been updated, otherwise it will only be me and you farming on your blockchain, and that does not really makes sense 😁

Not sure if you have a Discord server or some other means of communication, but you SHOULD create something like this as well.

Nevertheless I will keep farming lotus until the timelord is switched off, but I do not see a bright future ahead if you do not take into consideration my advice.

Have a nice weekend 🙂 !
