### ISSUE TITLE
Pronouncing Lotus Blockchain as dead

### ISSUE THREAD

**Issue by gowke** [gowke/lotus-blockchain#11]
Its has been a wonder the timelord lasted a year without hiccups. Unfortunately it has become somewhat difficult to constantly tinker with it. I wish you luck in farming other projects and thank you for your support. 

It is time for Lotus Blockchain to join the fallen comrades.

**Comment by ageorge95** [comment]
Hi,

It has been an interesting year for sure.

Lotus has been one of the reasons I am now often checking on the IO usage of my farm's HDDs 😁 (that started as soon as I discovered the plot filter thing)

Maybe some relaunch will be next 🤔 ? We have not got any new chia fork since some time now.

Anyhow I wish you luck as well 🤝

**Comment by WarutaShinken** [comment]
@gowke do you reckon you could hand the project over to another fork dev in the community sometime in the future? we've had it happen with tad-blockchain before (Tad creator gave discord server and prefarm to BTCgreen-Network)

**Comment by gowke** [comment]
Its alive bros.... I dont mind actually!

**Comment by gowke** [comment]
> Hi,
> 
> It has been an interesting year for sure.
> 
> Lotus has been one of the reasons I am now often checking on the IO usage of my farm's HDDs grin (that started as soon as I discovered the plot filter thing)
> 
> Maybe some relaunch will be next thinking ? We have not got any new chia fork since some time now.
> 
> Anyhow I wish you luck as well handshake

Waruta and George, and everyone else, thanks a lot. Lotus lives another day actually. Three days it wouldn't budge. If it wasnt for you I think it would be toast as I wouldn't give it another try. I am dropping a link to telegram https://t.me/+nHcOkm17VTExZGI0 so we can have some proper communication channel!

**Comment by WarutaShinken** [comment]
Hi, nice to see you return! Is there a chance you could make a Discord server for Lotus as well? Most of the Chia forks community resides on there.
