### ISSUE TITLE
Is this project abandoned ?

### ISSUE THREAD

**Issue by ageorge95** [gowke/lotus-blockchain#8]
I see that the timelord has been working for a long time without hiccups, but that is not enough.

@gowke is there a roadmap for this fork ?

Also, I see that the codebase is the same as the current chia, you should release a version for your fork.

Thanks !

**Comment by gowke** [comment]
@ageorge95  Hi George, 

Thanks for keeping an eye out for the project. 
Next stage is marketing and adoption. Something every fork will struggle with inevitably (even Chia itself). 

I am playing around with something that should aid this. Lotus has its own target market as well. 

I will sure let you know what I was working on when it is anywhere near the presentable stage. Target is to work on it over the summer.

Many thanks!

**Comment by ageorge95** [comment]
To be honest, I was not expecting a response 😁

Thank you for taking the time and responding. From my POV at least, this fork is not yet abandoned and I'll keep farming it.

The reason I created the issue has been addressed, so I will close it now.
